[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/php-handler"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/php-handler"
  status = 200

[functions]
  directory = "netlify/functions"
